services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn --worker-class gevent -w 1 app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      pythonVersion: 3.11.8
